services:
  - type: web
    name: zent-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: node dist/src/main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: JWT_EXPIRES_IN
        value: 7d

      - key: CLOUDINARY_CLOUD_NAME
        value: dymm2mhrl

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: BREVO_API_KEY
        sync: false

      - key: BREVO_SENDER_EMAIL
        value: appzent@outlook.com

      - key: FRONTEND_URL
        value: https://zent-mu.vercel.app

      - key: STRIPE_SECRET_KEY
        sync: false